### ISSUE TITLE
Purpose and Docker usage

### ISSUE THREAD

**Issue by iwconfig** [sbrunner/scan-to-paperless#347]
Hello,

I'm unable to get the docker version of this to work. Running the following

    docker run --rm \
    --volume=$HOME/Paperless/scan:/source \
    --volume=$HOME/Paperless/consume:/destination \
    sbrunner/scan-to-paperless

only greets me with

    Welcome to scanned images document to paperless.

How am I supposed to run this `scan` command? When trying to `docker exec` the command in the container it complains about it not being in $PATH.

By the way, `--rm` and `--restart` are mutually exclusive, at least from Docker version 19.03.15.

Also, I might have a misunderstanding of the purpose of this tool. What does this bring to the table that [jonaswinkler/paperless-ng](/jonaswinkler/paperless-ng) doesn't already do on it's own?

**Comment by sbrunner** [comment]
Thanks => https://github.com/sbrunner/scan-to-paperless/pull/350

**Comment by sbrunner** [comment]
For the scan command, you should install the Python pip package scan-to-paperless:
https://github.com/sbrunner/scan-to-paperless#on-the-desktop

**Comment by sbrunner** [comment]
I never get a relay get a good result with paperless directly:
I never relay see those features
https://github.com/sbrunner/scan-to-paperless#features
In action directly in paperless, and with my tool, I can verify that everything is OK before create the PDF, and I can restart some steps with a different configuration if I want a better result.

**Comment by iwconfig** [comment]
I see! That makes sense. Thank you for the answer.
