### ISSUE TITLE
Does not set --batch parameter

### ISSUE THREAD

**Issue by MajestyIV** [sbrunner/scan-to-paperless#369]
I get the following error message when I try to start scanning. For some reason it does not set the --batch parameter. Any suggestions?

`
scanimage --device=hpaio:/net/Officejet_6500_E710a-f?ip=10.5.50.35 --format=png --mode=color --resolution=300 --source=ADF
scanimage: output is not a file, exiting
Command '['scanimage', '--device=hpaio:/net/Officejet_6500_E710a-f?ip=10.5.50.35', '--format=png', '--mode=color', '--resolution=300', '--source=ADF']' returned non-zero exit status 1.
`

**Comment by sbrunner** [comment]
Strange, which version do you use? What exact command do you use to lunch the `scan` command?

**Comment by MajestyIV** [comment]
I tried `scan` and `scan --mode double`

Version is 1.7.0

**Comment by MajestyIV** [comment]
Nevermind, you fixed this already. My version is old.
