### ISSUE TITLE
Crop image

### ISSUE THREAD

**Issue by MajestyIV** [sbrunner/scan-to-paperless#370]
Could you explain, how the cropping works? I have a big black area at the bottom of each scan which leads to an error.

`'NoneType' object has no attribute 'shape'`

Once I remove the black area by hand, it starts processing correct.

**Comment by sbrunner** [comment]
I do content detection with cv2.findContours ...
Details: https://github.com/sbrunner/scan-to-paperless/blob/test/scan_to_paperless/process.py#L324-L353
But it effectively considers that the background is black
To avoid some issue with scanner artifacts, you can add a mask.png file in the scan folder, it should be a grayscale image, and the black part will be ignored in the content detection and in the deskew, but not removed.

**Comment by MajestyIV** [comment]
I think, there is an issue with my scanner. When using --mode=one there is no problem with the image. I will investigate this on my own. 
Thanks.
