### ISSUE TITLE
Green boxes

### ISSUE THREAD

**Issue by MajestyIV** [sbrunner/scan-to-paperless#374]
Is there a way to remove the green boxes around the content for the final result?

**Comment by sbrunner** [comment]
You shouldn't have any green boxes in the result, do you do anything special?

**Comment by MajestyIV** [comment]
I don't think so. Here is my config.

I made a test scan so you can see the final result that ends up in paperless-ng

https://1drv.ms/b/s!AhMBSDDEVkJrgf5SUFIA-1Fa3rwnbQ?e=Txssgf

`
# yaml-language-server: $schema=https://raw.githubusercontent.com/sbrunner/scan-to-paperless/master/scan_to_paperless/config_schema.json

scan_folder: /home/dino/paperless/scan/
scanimage_arguments: # Additional argument passed to the scanimage command
  - --device=hpaio:/net/Officejet_6500_E710a-f?ip=10.5.50.35
  - --format=png
  - --mode=color
  - --resolution=300
default_args:
  ## Level
  # true: => do level on 15% - 85% (under 15 % will be black above 85% will be white)
  # false: => 0% - 100%
  # <number>: => (0 + <number>)% - (100 - number)%
  level: False
  # If no level specified, do auto level
  auto_level: False
  # min level if no level end no autolovel
  min_level: 15
  # max level if no level end no autolovel
  max_level: 95

  ## Crop
  no_crop: False # Don't do any crop
  marging_horizontal: 9 # mm, the horizontal margin used on autodetect content
  marging_vertical: 6 # mm, the vertical margin used on autodetect content
  dpi: 300 # The DPI used to convert the mm to pixel

  # Sharpen
  sharpen: True # Do the sharpen

  # Dither
  dither: True # Do the dither

  ## OCR
  tesseract: False # Use tesseract to to an OCR on the document
  tesseract_lang: deu+eng # The used language
`

**Comment by sbrunner** [comment]
This looks correct, but in the standard way at the end of the first pass you should have one file in the `3-crop` folder with the green boxes, and one in the base folder without them.
For the next steps, it's the file at the base folder who is taken, you didn't copy one file to another?

**Comment by MajestyIV** [comment]
No, I did not copy any files. The file in the base folder has the green boxes already.

**Comment by sbrunner** [comment]
Do you use the Docker image to do the processing?, At which version?

**Comment by MajestyIV** [comment]
Yes, I do use the docker image. I build it from the master branche.

**Comment by sbrunner** [comment]
Effectively, there is an issue on the master branch, can you test the `test` branch?

**Comment by MajestyIV** [comment]
Oh, sorry, I'm on test already. This is the default branch. The image in the base folder has the green boxes and the image in the 3-crop folder has none.

**Comment by sbrunner** [comment]
And your at latest revision?

**Comment by MajestyIV** [comment]
I just pulled it again and rebuild the docker container. Same result. When I change the config to `no_crop: True` there are green boxes in the 3-crop folder aswell.

**Comment by Joker45b** [comment]
Same here. Green Boxes in 3Crop and all the following Images.  Using Docker test.

**Comment by sbrunner** [comment]
Effectively, I should take time to do deeper investigations...

**Comment by Joker45b** [comment]
No Problem...  I just wrote to show its not a single Problem..  THX for your work and sharing scan-to-paperless

**Comment by Joker45b** [comment]
Thx for the update. Now the green Boxes are gone by setting no_crop to true.  By using false they are still there. I hope it helps

**Comment by sbrunner** [comment]
Thanks for the feedback, I will investigate more (I can reproduce it :-) )

**Comment by Joker45b** [comment]
I can confirm..  You fix it. Big Thx

**Comment by MajestyIV** [comment]
Great! Now I need a new scanner. Sane has some problems with my HP Deskjet 6500a when scanning ADF.

**Comment by sbrunner** [comment]
Thanks for your feedback :-) pushed to master!
