### ISSUE TITLE
Best way for skipping REMOVE_TO_CONTINUE removal?

### ISSUE THREAD

**Issue by lhl** [sbrunner/scan-to-paperless#920]
Hi, just giving this project a spin, and it looks like it does almost exactly what I'd like it do (getting pages from my ADF scanner into paperless-ngx w/ some cleanup and minimal hassle), except I'd like to be able to skip having to remove the REMOVE_TO_CONTINUE file manually, and just let it passthrough if possible?

I looked in the config doc: https://github.com/sbrunner/scan-to-paperless/blob/test/config.md but couldn't see a flag to do that. Did I miss something, or if not, is there a recommended/suggested way to do that?

My setup is that I have a network accessible scanner, an Epson DS-571W, and I am running the scan-to-paperless client and server on my NAS (which is also running paperless-ngx w/ docker compose). In my ideal scenario, I'd like to hook up the scan button (maybe figuring out [scanbd](https://wiki.archlinux.org/title/Scanner_Button_Daemon)? or adding a button to the paperless-ngx UI to run `scan`...

**Comment by sbrunner** [comment]
We should add an option for that :-)
